---
title: "econ-homework4"
author: "Kristin Gill and Alyssa Kibbe"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(kableExtra)
```

```{r}
# read in the data
damages <- read_csv(here("data", "damages.csv"))

warming <- read_csv(here("data", "warming.csv")) %>% 
  rename("time" = "X1")
```

```{r}
# graphing damages vs. warming
ggplot(data = damages, aes(x = warming,
                           y = damages)) +
  geom_point() +
  theme_minimal()+
  labs(x = "Warming (Degrees Celsius)",
       y = "Damages (Dollars)") +
  geom_smooth(method = "lm",
              formula = y ~ x + I(x^2),
              color = "black",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) +
  ggpubr::stat_regline_equation(label.x = 4, label.y = 100000000000000, formula = y ~ x + I(x^2))
```

```{r}
# 2 damages under different scenarios
warming_scenarios <- warming%>% 
  mutate(damages_baseline = ((warming_baseline*warming_baseline)*(2e13))-((3e12)*warming_baseline)) %>% 
  mutate(damages_pulse = ((warming_pulse*warming_pulse)*(2e13))-((3e12)*warming_pulse)) %>% 
  mutate(damages_difference = (damages_pulse - damages_baseline)) %>% 
  mutate(diff_per_ton = (damages_difference/35e9))

# plots
# damages over time without the pulse
base <- ggplot(data = warming_scenarios, aes(x = year,
                                     y = damages_baseline)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Time(years)",
       y = "Baseline Damages ($)",
       title = "Projected Baseline Damages")

# damages over time WITH the pulse
pulse <- ggplot(data = warming_scenarios, aes(x = year,
                                     y = damages_pulse)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Time(years)",
       y = "Pulse Damages ($)",
       title = "Projected Pulse Damages")

# the difference in damages over time that arises from the pulse
diff <- ggplot(data = warming_scenarios, aes(x = year,
                                     y = damages_difference)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Time(years)",
       y = "Difference in Damages ($)",
       title = "Difference due to Pulse")

# the difference in damages over time from the pulse per ton of CO2
diff_per_ton <- ggplot(data = warming_scenarios, aes(x = year,
                                     y = diff_per_ton)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Time(years)",
       y = "Difference ($/Ton CO2)",
       title = "Difference/Ton of CO2")

graph_compound <- ((base|pulse)/(diff|diff_per_ton)) & plot_layout(guides = "collect")
graph_compound
```

```{r}
#3 SCC
r <- seq.int(from = 0.01, to = 0.1, by = 0.01)
y <- NULL

for (i in r) {
  pv <- sum((warming_scenarios$diff_per_ton/(1 + i)^warming_scenarios$time))
  y <- rbind(y, c(i, pv))
}

scc <- data.frame(y) %>% 
  rename("discount_rate" = "X1") %>% 
  rename("scc" = "X2") %>% 
  mutate(percent_r = 100*discount_rate) %>% 
  select(!discount_rate)

# plotting it
ggplot(data = scc, aes(x = percent_r,
                       y = scc)) +
  geom_line()+
  theme_minimal() +
  labs(x = "Discount Rate (%)",
       y = "SCC (Dollars)")

scc_new <- scc %>% 
  rename("Discount Rate" = "percent_r") %>% 
  rename("SCC" = "scc")

kbl(scc_new) %>% 
   kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F)
```

```{r}
#4 

r_ramsey <- (0.001 + (2*0.01))

x <- NULL

for (i in r_ramsey) {
  pv <- sum((warming_scenarios$diff_per_ton/(1 + i)^warming_scenarios$time))
  x <- rbind(x, c(i, pv))
}

point <- data.frame(x) %>% 
  mutate(r = X1*100)

# discount rate is 0.021 (2.1%) and SCC is 69.93572

ggplot(data = scc, aes(x = percent_r,
                       y = scc)) +
  geom_line()+
  theme_minimal() +
  labs(x = "Discount Rate (%)",
       y = "SCC (Dollars)") +
  geom_point(data = point, aes(x = r,
                           y = X2),
             color = "blue",
             size = 3)
```

```{r}
#5 

# Policy A: BAU
BAU <- warming %>% 
  select(time, year, warming_baseline) %>% # probability 0.5
  mutate(warming_1.5 = (warming_baseline*1.5)) %>% # probability 0.5
  mutate(damages_baseline = ((warming_baseline*warming_baseline)*(2e13))-((3e12)*warming_baseline)) %>% 
  mutate(damages_1.5 = ((warming_1.5*warming_1.5)*(2e13))-((3e12)*warming_1.5)) %>% 
  mutate(expected_damage = (0.5*damages_baseline) + (0.5*damages_1.5))

pv_A <- sum((BAU$expected_damage/(1 + 0.02)^BAU$time))
pv_A

# test for policy A
pv_A1 <- sum((BAU$damages_baseline/(1 + 0.02)^BAU$time))
pv_A1

pv_A2 <- sum((BAU$damages_1.5/(1 + 0.02)^BAU$time))
pv_A2

pv_expected <- (0.5*pv_A1) + (0.5*pv_A2)
pv_expected

# Policy B
policy_b <- warming %>% 
  select(time, year, warming_baseline) %>% 
  mutate(warming_baseline = case_when(
    year > 2050 ~ 1.29,
    TRUE ~ as.numeric(as.character(warming_baseline))
  )) %>% 
  mutate(damages = ((warming_baseline*warming_baseline)*(2e13))-((3e12)*warming_baseline))

pv_B <- sum((policy_b$damages/(1 + 0.02)^policy_b$time))
pv_B

x <- (pv_A - pv_B)
x
```

